name: ra-ml
channels:
  - pytorch
  - anaconda
  - r
  - conda-forge
  - defaults
dependencies:
  - numpy=1.15
  - pandas=0.23.4
  - pip=18.1
  - rpy2=2.9.3
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - tqdm=4.29.1
